name: my_project
version: 1.0
config-version: 2
 
profile: my_profile
 
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
 
clean-targets:
  - "target"
  - "dbt_packages"
 
models:
  my_project:
    +materialized: view